### ISSUE TITLE
关于图片处理问题

### ISSUE THREAD

**Issue by imnekoda** [Xwdit/RainyBot-API#2]
太棒了！！不过写插件的时候有一个疑问，有一个疑问请问应该如何从一个FriendMessageEven事件里获取到图片，并转发到指定的群里

**Comment by Xwdit** [comment]
> 太棒了！！不过写插件的时候有一个疑问，有一个疑问请问应该如何从一个FriendMessageEven事件里获取到图片，并转发到指定的群里

```gdscript
var group = Group.init(群号) #创建一个代表某群的实例
var arr = event.get_message_array(ImageMessage) #获取事件中所有指定类型的消息（此处为ImageMessage类，将返回一个数组）
if arr.size()>0: #判断是否成功从事件中获取到图片消息
    group.send_message(arr[0]) #发送事件中的第一个图片消息到群的实例
```

**Comment by imnekoda** [comment]
> > 太棒了！！不过写插件的时候有一个疑问，有一个疑问请问应该如何从一个FriendMessageEven事件里获取到图片，并转发到指定的群里
> 
> ```gdscript
> var group = Group.init(群号) #创建一个代表某群的实例
> var arr = event.get_message_array(ImageMessage) #获取事件中所有指定类型的消息（此处为ImageMessage类，将返回一个数组）
> if arr.size()>0: #判断是否成功从事件中获取到图片消息
>     group.send_message(arr[0]) #发送事件中的第一个图片消息到群的实例
> ```

感谢您的回复，看起来似乎是正常发送了。但是在群里却没有正常的响应，控制台打印的信息看起来没有任何问题，我本以为触发的风控，但重新注册账号依旧出现了此问题，尚不清楚其他人能否复现此问题
![9L1EZW29Z 7$}FWJ7@KY9S6](https://user-images.githubusercontent.com/84014558/149062468-8ea0dde4-1efe-4c23-a324-b1a5aa6c5152.png)
![66RQZ($UYUE05UJRLM`9O~Q](https://user-images.githubusercontent.com/84014558/149062499-93f3d578-2fcb-4e8e-b6fd-9969d67038c5.png)

**Comment by Xwdit** [comment]
经测试当前版本一切正常，因此暂时关闭此Issue
